@namespace=ath-api-exemplo
@versao=1.0.0-alpha2
@cenario=teste api

POST http://localhost:3000/teste-carga/executar
content-type: application/json

{
    "preRequest": [
        {
            "request": {
                "url": "http://localhost:3000/test/parametro1",
                "method": "GET",
                "headers": {
                    "content-type": "application/json",
                    "cookie": "teste=asdfsadfasdf"
                }
            },
            "environment": [
                {
                    "nome": "number1",
                    "campo": "$.numero1"
                }
            ]
        },
        {
            "request": {
                "url": "http://localhost:3000/test/parametro2",
                "method": "GET",
                "headers": {
                    "content-type": "application/json"
                }
            },
            "environment": [
                {
                    "nome": "number2",
                    "campo": "$.numero2"
                }
            ]
        }
    ],
    "testeDeCarga": {
        "url": "http://localhost:3000/test/soma",
        "connections": 1,
        "pipelining": 1,
        "amount": 5,
        "method": "post",
        "title": "execução de exemplo",
        "body": {
            "numero1": "<<number1>>",
            "numero2": "<<number2>>"
        },
        "headers": {
            "content-type": "application/json"
        }
    },
    "posRequest": [{
        "request": {
                "url": "http://localhost:3000/test/parametro1",
                "method": "GET",
                "headers": {
                    "content-type": "application/json"
                }
            }
    }],
    "namespace": "{{namespace}}",
    "versao": "{{versao}}",
    "cenario": "{{cenario}}"
}

###


GET  http://localhost:3000/test/parametro1 
content-type: application/json
###

GET  http://localhost:3000/test/parametro2 
content-type: application/json
###

POST  http://localhost:3000/test/soma 
content-type: application/json

{
    "numero1": 50,
    "numero2": 30
}

###
@keyReq=1702574480867-de85057c-46b3-4ba0-a99f-1a4492ffe032
GET  http://localhost:3000/teste-carga/buscar/{{keyReq}}/namespace/{{namespace}}/versao/{{versao}}/cenario/{{cenario}}
content-type: application/json

###
GET  http://localhost:3000/teste-carga/buscar/{{keyReq}}/namespace/{{namespace}}/versao/{{versao}}
content-type: application/json

###